.Dd Jan 6, 2011
.Os Unix
.Dt CLU 1
.Sh NAME
.Nm clu
.Nd Describes various interesting aspects (facts) about the current system.
.Sh SYNOPSIS
.Nm
.Op Cm --help | -h
.Op Cm --version
.Op Cm --verbose | -v
.Sh DESCRIPTION
.Bl -tag
.It Cm --help -h
List the help screen for the command.
.It Cm --version
Print the version of the command.
.It Cm --verbose -v
Run in verbose mode.
.El
.Sh ENVIRONMENT
.Nm
uses PATH to find executables.
.Sh FILES
There are no config files for
.Nm\&,
but it does read from a number of system files to function.
.Sh EXAMPLES
Not written yet.
.Sh DIAGNOSTICS
Not written yet.
.Sh HISTORY
clu is the 4th or 5th incarnation of this idea. I finally gave up on 2 different incarnations of shell script -
bash AND fish. The deployment is easy(er) but the programming is AWFUL. Python it is. (I wish Python had the same deployment model of Go...)
The original was call "whatami", as opposed to "whoami" for users. Its also been called
.Qq hwid
,
.Qq kgb
, and
.Qq gru
\&.
The russian spy theme became inappropriate, so I settled on
.Nm\&.
.Sh AUTHORS
.An Hunter Matthews Aq hunter@unix.haus
is to blame on this one.
.Sh BUGS
I'm sure there are many.
