= clu(1)
:doctype: manpage
:man manual: General Commands Manual
:man source: clu
:docdate: January 6, 2011
:page-layout: base

== NAME

clu - Describes various interesting facts about the current system.

== SYNOPSIS

*clu* [*--help* | *--version* | *--debug* | *--net*]

*clu* *collector*

*clu* *facts* [*--tier*, *-t* {*1* | *2* | *3*}] [*--out* {*dots* | *shell* | *json*}]

*clu* *requires* {*list* | *check*}

== DESCRIPTION

*clu* is a tool for reporting various facts about a system. It reads well known system files and runs programs to collect the information. It was created because other tools in this category (and there are _many_) either tried to report too much (overwhelming a busy sysadmin) or far too little (causing the sysadmin to have to run other commands for a complete picture). It is therefore strongly opinionated - what it outputs and how that is formatted are pretty much at the opinion of the author.

== OPTIONS

The following global options are supported. Individual commands may have their own specific options.

*--help, -h*::
    List the help screen for the command and exit.

*--version*::
    Print the version of the command and exit.

*--verbose, -v*::
    Run in verbose mode.

*--debug*::
    Print extra debugging output (not really implemented yet).

*--net*::
    Allow access to the network. Some steps require more than just a DNS query (such as talking to Device42 inventory system or updating the DNF/APT data - this flag allows such access).

== COMMANDS

*collector*::
    Create a compressed *tar*(1) archive of all the required file and program outputs used by *clu*. This facilitates both testing and debugging without needing to be fully networked all the time or remote debugging. The archive will be named /tmp/clu_<hostname>.tgz.

*facts* [*--tier*, *-t* {*1* | *2* | *3*}] [*--out* {*dots* | *shell* | *json*}]::
    Report various facts about the computer. This includes details of the OS, hardware (virtual or physical), networking, etc.
+
The *--tier* controls tier of facts (more and more details at higher / larger number tiers...) are printed.
+
Output is controlled with the *--output* flag and a single required argument of {*dots* | *shell* | *json*} with the default being dots.

*requires* {*check* | *list*}::
    List or check the required files, programs and api's required for the program to run.

== HISTORY

clu is the 4th or 5th incarnation of this idea, going back to 2011. I finally gave up on 2 different incarnations of shell script. The deployment is easier but the programming is AWFUL. Pure python zipapps solve the deployment problem (mostly). (I wish Python had the same deployment model of Go...) Names have varied considerably over the years. Earlier incarnations strongly influenced the `collector` command and being able to test the parsers without being logged in to networked systems.

== AUTHORS

Hunter Matthews <hunter@unix.haus> is to blame on this one.
